const constants = {

    // events
    ROUTE_CHANGED_EVENT: 'ROUTE_CHANGED_EVENT',
    CHANGE_EVENT: 'change',
    MISSION_STARTED: 'MISSION_STARTED',
    MISSION_STOPPED: 'MISSION_STOPPED',
    MESSAGE_ADDED: 'MESSAGE_ADDED',
    REMOVE_MESSAGE: 'REMOVE_MESSAGE',
    REMAINING_MISSION_TIME_CHANGED: 'REMAINING_MISSION_TIME_CHANGED',
    MISSION_TIMEOUT : 'MISSION_TIMEOUT',
    SCIENCE_COUNTDOWN_TIMER_CHANGED :  'SCIENCE_COUNTDOWN_TIMER_CHANGED',


    // message ids
    NOT_READY_MSG : 'NOT_READY_MSG'
};

window.constant = constants;
module.exports = constants;