window.__astConst = module.exports = {
    'GOOD_OXYGEN': 'GOOD_OXYGEN',
    'WARN_OXYGEN': 'WARN_OXYGEN',
    'CRITICAL_OXYGEN': 'CRITICAL_OXYGEN',
    "LOW_RESP_RATE": 'LOW_RESP_RATE',
    'HIGH_RESP_RATE': 'HIGH_RESP_RATE',

    SET_BREATH_RATE: 'SET_BREATH_RATE',
    SET_HEART_RATE: 'SET_HEART_RATE',
    SET_OXYGEN_LEVEL : 'SET_OXYGEN_LEVEL',
    SET_OXYGEN_CONSUMPTION : 'SET_OXYGEN_CONSUMPTION'
};