module.exports = Object.freeze({
    MISSION_TIME_SYNC: 'MISSION_TIME_SYNC',
    MISSION_STARTED_EVENT: 'MISSION_STARTED_EVENT',
    MISSION_STOPPED_EVENT: 'MISSION_STOPPED_EVENT',
    START_TASK: 'START_TASK',
    INTRODUCTION_READ: 'INTRODUCTION_READ'
});
